name: Go Coverage Badge
description: Generate coverage badge for go projects
author: tj-actions
inputs:
  filename:
    description: 'File containing the tests output (default: "coverage.out")'
    required: true
    default: coverage.out
  color:
    description: 'Color of the badge - green/yellow/red'
    required: false
  green:
    description: 'At what percentage does the badge becomes green instead of yellow (default: 70)'
    required: false
  target:
    description: 'Target file (default "README.md")'
    required: false
  text:
    description: 'Text on the left side of the badge (default: "Coverage")'
    required: false
  value:
    description: 'Text on the right side of the badge'
    required: false
  yellow:
    description: 'At what percentage does the badge becomes yellow instead of red (default 30)'
    required: false
  output:
    description: 'Output markdown file to update (default: "README.md")'
    required: false
    default: 'README.md'
  username:
    description: 'Username of the github user (default: github.actor)'
    required: false
    default: 'github-actions[bot]'
  email:
    description: 'Username of the github user (default: github.actor)'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

runs:
  using: 'composite'
  steps:
    - run: |
        EXTRA_ARGS=""

        if [[ -n '${{ inputs.color }}'  ]]; then
          EXTRA_ARGS+="-color=${{ inputs.color }}"
        fi

        if [[ -n '${{ inputs.green }}'  ]]; then
          EXTRA_ARGS+="-green=${{ inputs.green }}"
        fi

        if [[ -n '${{ inputs.target }}'  ]]; then
          EXTRA_ARGS+="-target=${{ inputs.target }}"
        fi

        if [[ -n '${{ inputs.text }}'  ]]; then
          EXTRA_ARGS+="-text=${{ inputs.text }}"
        fi

        if [[ -n '${{ inputs.value }}'  ]]; then
          EXTRA_ARGS+="-value=${{ inputs.value }}"
        fi

        if [[ -n '${{ inputs.yellow }}'  ]]; then
          EXTRA_ARGS+="-yellow=${{ inputs.yellow }}"
        fi

        curl -sf https://gobinaries.com/github.com/AlexBeauchemin/gobadge@v0.2.0 | PREFIX=. sh

        gobadge -filename=${{ inputs.filename }} $EXTRA_ARGS
      id: coverage-badge-go
      shell: bash

branding:
  icon: check-circle
  color: white
